//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : MakerBase {
        
        /// <summary>The LightSense module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.LightSense lightSense;
        
        /// <summary>The Ethernet ENC28 module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.EthernetENC28 ethernetENC28;
        
        /// <summary>The Character Display module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.CharacterDisplay characterDisplay;
        
        /// <summary>The Temp&Humidity module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.TempHumidity tempHumidity;
        
        /// <summary>The Relay X1 module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.RelayX1 relayX1;
        
        /// <summary>The LED7R module (not connected).</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7R led7R;
        
        /// <summary>The Tunes module using socket 7 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Tunes tunes;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZHydra Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZHydra)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZHydra();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            Microsoft.SPOT.Debug.Print("The module \'lightSense\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'ethernetENC28\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'characterDisplay\' was not connected in the designer and will be null." +
                    "");
            Microsoft.SPOT.Debug.Print("The module \'tempHumidity\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'relayX1\' was not connected in the designer and will be null.");
            Microsoft.SPOT.Debug.Print("The module \'led7R\' was not connected in the designer and will be null.");
            this.tunes = new GTM.GHIElectronics.Tunes(7);
        }
    }
}
